{
  "openapi": "3.0.1",
  "info": {
    "title": "Base API V1",
    "version": "v1"
  },
  "paths": {
    "/api/v1/users/login": {
      "post": {
        "summary": "login user",
        "tags": [
          "Users"
        ],
        "description": "Logs in a user",
        "parameters": [],
        "responses": {
          "200": {
            "description": "success",
            "content": {
              "application/json": {
                "schema": {
                  "example": {
                    "success": true,
                    "payload": {
                      "id": 96621,
                      "email": "randall@wilkinson.biz",
                      "first_name": "Eda",
                      "last_name": "Maggio",
                      "name": "Eda Maggio",
                      "token": {
                        "id": 32136,
                        "created_at": "2023-03-16 18:46:40 UTC",
                        "expiry": "2023-03-23 18:46:40 UTC",
                        "ip": null,
                        "revocation_date": null,
                        "updated_at": "2023-03-16 18:46:40 UTC",
                        "user_id": 96621,
                        "value": "1BzSSzFArKGopyZSMwKi2r2RKoLJdkv2xa"
                      }
                    },
                    "status": 200
                  }
                }
              }
            }
          },
          "401": {
            "description": "Error: Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/unauthenticated_user"
                }
              }
            }
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/login_user"
              }
            }
          }
        }
      }
    },
    "/api/v1/users/logout": {
      "delete": {
        "summary": "logout user",
        "tags": [
          "Users"
        ],
        "description": "Logs out a user",
        "security": [
          {
            "bearer_auth": []
          }
        ],
        "responses": {
          "200": {
            "description": "logged out user",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/logout_user"
                }
              }
            }
          },
          "401": {
            "description": "authentication failed",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/bad_credentials"
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/users/me": {
      "get": {
        "summary": "me user",
        "tags": [
          "Users"
        ],
        "description": "Display the current user",
        "security": [
          {
            "bearer_auth": []
          }
        ],
        "responses": {
          "200": {
            "description": "user profile",
            "content": {
              "application/json": {
                "schema": {
                  "example": {
                    "payload": {
                      "id": 96621,
                      "email": "randall@wilkinson.biz",
                      "first_name": "Eda",
                      "last_name": "Maggio",
                      "name": "Eda Maggio"
                    },
                    "status": 200
                  }
                }
              }
            }
          },
          "401": {
            "description": "authentication failed",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/bad_credentials"
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/users/create": {
      "post": {
        "summary": "create user",
        "tags": [
          "Users"
        ],
        "description": "Create a new user",
        "parameters": [],
        "responses": {
          "201": {
            "description": "user created",
            "content": {
              "application/json": {
                "schema": {
                  "example": {
                    "success": true,
                    "payload": {
                      "id": 96621,
                      "email": "randall@wilkinson.biz",
                      "first_name": "Eda",
                      "last_name": "Maggio",
                      "name": "Eda Maggio",
                      "phone": "1524887662"
                    },
                    "status": 201
                  }
                }
              }
            }
          },
          "400": {
            "description": "invalid request",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/error_saving_user"
                }
              }
            }
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/create_user"
              }
            }
          }
        }
      }
    }
  },
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "components": {
    "securitySchemes": {
      "bearer_auth": {
        "type": "http",
        "scheme": "bearer",
        "bearer_format": "string"
      }
    },
    "schemas": {
      "create_user": {
        "type": "object",
        "properties": {
          "first_name": {
            "type": "string",
            "nullable": false
          },
          "last_name": {
            "type": "string",
            "nullable": false
          },
          "email": {
            "type": "string",
            "nullable": false
          },
          "phone": {
            "type": "string",
            "nullable": false
          },
          "password": {
            "type": "string",
            "nullable": false
          },
          "password_confirmation": {
            "type": "string",
            "nullable": false
          }
        },
        "required": [
          "first_name",
          "last_name",
          "email",
          "phone",
          "password",
          "password_confirmation"
        ]
      },
      "login_user_payload": {
        "type": "object",
        "properties": {
          "success": {
            "type": "boolean",
            "example": true
          },
          "payload": {
            "type": "object",
            "properties": {
              "user": {
                "type": "object",
                "properties": {
                  "id": {
                    "type": "integer",
                    "example": 76485
                  },
                  "email": {
                    "type": "string",
                    "example": "shirlee_rolfson@volkman.info"
                  },
                  "first_name": {
                    "type": "string",
                    "example": "Zachary"
                  },
                  "last_name": {
                    "type": "string",
                    "example": "Reinger"
                  },
                  "name": {
                    "type": "string",
                    "example": "Zachary Reinger"
                  },
                  "token": {
                    "type": "object",
                    "properties": {
                      "id": {
                        "type": "integer",
                        "example": 40731
                      },
                      "created_at": {
                        "type": "string",
                        "example": "2023-03-16 18:46:40 UTC"
                      },
                      "expiry": {
                        "type": "string",
                        "example": "2023-03-23 18:46:40 UTC"
                      },
                      "ip": {
                        "type": "any",
                        "example": null
                      },
                      "revocation_date": {
                        "type": "any",
                        "example": null
                      },
                      "updated_at": {
                        "type": "string",
                        "example": "2023-03-16 18:46:40 UTC"
                      },
                      "user_id": {
                        "type": "integer",
                        "example": 76485
                      },
                      "value": {
                        "type": "string",
                        "example": "1GvnANRaysDi7qyvx6tu5k82GL63hzNiRN"
                      }
                    }
                  }
                }
              }
            }
          },
          "token": {
            "type": "object",
            "properties": {
              "id": {
                "type": "integer",
                "example": 40731
              },
              "created_at": {
                "type": "string",
                "example": "2023-03-16 18:46:40 UTC"
              },
              "expiry": {
                "type": "string",
                "example": "2023-03-23 18:46:40 UTC"
              },
              "ip": {
                "type": "any",
                "example": null
              },
              "revocation_date": {
                "type": "any",
                "example": null
              },
              "updated_at": {
                "type": "string",
                "example": "2023-03-16 18:46:40 UTC"
              },
              "user_id": {
                "type": "integer",
                "example": 76485
              },
              "value": {
                "type": "string",
                "example": "1GvnANRaysDi7qyvx6tu5k82GL63hzNiRN"
              }
            }
          },
          "status": {
            "type": "integer",
            "example": 200
          }
        }
      },
      "unauthenticated_user": {
        "type": "object",
        "properties": {
          "success": {
            "type": "boolean",
            "example": false
          },
          "errors": {
            "type": "string",
            "example": "User not authenticated"
          },
          "status": {
            "type": "integer",
            "example": 401
          }
        }
      },
      "logout_user": {
        "type": "object",
        "properties": {
          "success": {
            "type": "boolean",
            "example": true
          },
          "payload": {
            "type": "string",
            "example": "You have been logged out"
          }
        }
      },
      "login_user": {
        "type": "object",
        "properties": {
          "email": {
            "type": "string",
            "required": true,
            "description": "email required"
          },
          "password": {
            "type": "string",
            "required": true,
            "description": "password required"
          }
        },
        "required": [
          "email",
          "password"
        ]
      },
      "bad_credentials": {
        "type": "object",
        "properties": {
          "error": {
            "type": "string",
            "example": "Bad Credentials"
          },
          "status": {
            "type": "integer",
            "example": 401
          }
        }
      },
      "me": {
        "type": "object",
        "properties": {
          "success": {
            "type": "boolean",
            "example": true
          },
          "payload": {
            "type": "object",
            "properties": {
              "id": {
                "type": "integer",
                "example": 76485
              },
              "email": {
                "type": "string",
                "example": "shirlee_rolfson@volkman.info"
              },
              "first_name": {
                "type": "string",
                "example": "Zachary"
              },
              "last_name": {
                "type": "string",
                "example": "Reinger"
              },
              "name": {
                "type": "string",
                "example": "Zachary Reinger"
              }
            }
          }
        }
      },
      "create_user_payload": {
        "type": "object",
        "properties": {
          "success": {
            "type": "boolean",
            "example": true
          },
          "payload": {
            "type": "object",
            "properties": {
              "id": {
                "type": "integer",
                "example": 76485
              },
              "email": {
                "type": "string",
                "example": "shirlee_rolfson@volkman.info"
              },
              "first_name": {
                "type": "string",
                "example": "Zachary"
              },
              "last_name": {
                "type": "string",
                "example": "Reinger"
              },
              "name": {
                "type": "string",
                "example": "Zachary Reinger"
              },
              "phone": {
                "type": "string",
                "example": "8666509470"
              }
            }
          }
        }
      },
      "error_saving_user": {
        "type": "object",
        "properties": {
          "success": {
            "type": "boolean",
            "example": false
          },
          "errors": {
            "type": "string",
            "example": "There was a problem creating a new user"
          },
          "status": {
            "type": "integer",
            "example": 400
          }
        }
      }
    }
  },
  "servers": [
    {
      "url": "http://{localHost}",
      "variables": {
        "localHost": {
          "default": "localhost:3000"
        }
      }
    },
    {
      "url": "https://{staging}",
      "variables": {
        "staging": {
          "default": "set-staging-url-in-swagger_helper.rb"
        }
      }
    },
    {
      "url": "https://{production}",
      "variables": {
        "production": {
          "default": "set-production-url-in-swagger_helper.rb"
        }
      }
    }
  ]
}